backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "postcards"
    label: "Postcards"
    folder: "content/products/postcards"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string", default: "$1.04" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Route", name: "route", widget: "string", default: "/products/postcards/" }
      - { label: "SEO Title", name: "seoTitle", widget: "string" }
      - { label: "SEO Description", name: "seoDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
